name: PR Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install PulseAudio
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pulseaudio

      # --- 여기에 PulseAudio 서버 시작 스텝 추가 ---
      - name: Start PulseAudio Server
        run: pulseaudio --start --exit-idle-time=-1 # 백그라운드에서 데몬으로 시작하고 자동 종료 방지
      # 또는 pulseaudio -D 를 사용할 수도 있습니다.
      # --- PulseAudio 서버 시작 스텝 끝 ---

      - name: Run tests
        run: npm run test
